### ISSUE TITLE
Pingpong/ShaderPass inconsistent results in Safari & FF

### ISSUE THREAD

**Issue by andrewleek-droplab** [martinlaxenaire/curtainsjs#67] opened 2020-11-10 22:43 UTC
Hey Martin,

I've got a bit of an odd one for you.  I wish I could provide more details but basically I'm getting inconsistent results when viewing the following in Safari on desktop:

https://jsfiddle.net/AndrewLeek/fgLjo1y3/1/

*Keep in mind you need set "Disable Cross-Origin Restrictions" to true in the Develop menu for the image to load...

What i am seeing is that when I hit "Run" button sometimes the displacement stuff works and sometimes it does not.  Often I have to hit Run many times to see this.

Unfortunately I cant share the local project I'm working on, so I am sharing this fiddle which seems to show some of the behavior I am seeing locally.  Locally, I can also tell you that in Safari and FF I cant get the displacement stuff to work on initial load.  But, I have additional logic where I destroy and rebuild all the planes/shaderpasses and on rebuild it does work in FF and occasionally in Safari...  I know that is all very vague, but any insight would be much appreciated.

Thanks,
Andrew

**Comment by martinlaxenaire** [comment] 2020-11-12 15:32
Hey @andrewleek-droplab, 

I did indeed stumble upon that erratic bug some times. I'm working on it. Version 7.3 should improve the way the PingPongPlanes are managed and I hope it could fix this issue. See updated fiddle: https://jsfiddle.net/qacbvgue/
See also the new example: https://www.curtainsjs.com/examples/gsap-click-to-fullscreen-gallery/

Let me know if that solves your issue.

Cheers,

**Comment by andrewleek-droplab** [comment] 2020-11-13 01:55
Hey @martinlaxenaire ,

Thanks for the update!

Regarding the fiddle, in Safari it feels like it is working more often, but there is still times where it doesnt work at all.

In my local project, the v7.3.1 update did in fact fix things in FF, but in Safari things are still broken (although not as much)... 
It kind of feels like an order of ops situation or something where perhaps sometimes planes/shader passes are bound out of order (although honestly i dont know the internal workings well enough, its just a feeling).

I will keep testing on my end to see if I cant find something that points to consistent results one way or the other...

Nice new example btw!  I really like it!

**Comment by droplab** [comment] 2020-11-30 19:13
Hi, adding to this discussion the following example does not work in Safari v14. This example does work, albeit with poor performance, in Safari v13.

https://www.curtainsjs.com/examples/ping-pong-shading-flowmap/index.html

 Thanks for all the work on a great library!

**Comment by droplab** [comment] 2020-11-30 19:20
Further, I can confirm all other examples are working properly in Safari v14 except the ping-pong example. Thanks!

**Comment by martinlaxenaire** [comment] 2020-12-01 09:24
Hi @droplab, 

thanks for the input.

Could you please provide more feedback on this issue?
- What's your OS version?
- Any console warnings and/or errors?
- Is the https://www.curtainsjs.com/examples/gsap-click-to-fullscreen-gallery/ example working with the same setup?
- Is it running Webgl2.0? You can test with `curtains.isWebGL2()`

Thanks,

**Comment by joris-rotteveel** [comment] 2020-12-14 20:47
@martinlaxenaire, I am running into the exact same issue on the flowmap example. It seems to properly work when you mousedown adn then move around. otherwise it's either not working or erratic. The fullscreen gallery is not showing any flowmap at this stage. Running the example locally in Safari Version 13.1.3 (15609.4.1)  tells me it isn't using WebGL2.

Hope that's useful information?

**Comment by martinlaxenaire** [comment] 2020-12-15 08:59
Hi @joris-rotteveel, 

I've been working on this issue again end of last week.
I have not yet pushed the fix to the master repo, but the dev one is up to date: https://github.com/martinlaxenaire/curtainsjs/tree/dev

With this fix I am not able to reproduce the issue any more but I haven't tested it on Safari so I don't know if we can consider this is definitely fixed.
Anyway here is a link to a working fiddle: https://jsfiddle.net/nrbvfgu3/

As for the mousedown thing, this reminds me of this discussion: https://github.com/oframe/ogl/issues/75
Could it be a specific Safari bug?...

Cheers,

**Comment by joris-rotteveel** [comment] 2020-12-16 02:28
@martinlaxenaire, 

Unfortunately (with my setup), the issue remains the same. Interesting to see this is also an issue for OGL. As Gordonnl mentioned, it could be an "optimisation" that Safari does on the mouse-events. Click and drag seems to create the desired effect.

**Comment by martinlaxenaire** [comment] 2020-12-16 12:24
Thanks for the feedback and the fiddle @joris-rotteveel, 

this would mean then that the 97a9b55aabd89254af616c1a349f86de7f5d4108 commit has actually fixed the WebGL erratic behavior, and that we are now facing a browser-related issue. That would be a relief. Can you confirm this @andrewleek-droplab?

Cheers,

**Comment by martinlaxenaire** [comment] 2021-03-17 12:28
Closing this issue as it seems to be fixed.

**Closed by martinlaxenaire** 2021-03-17 12:28 UTC
Labels: bug, question
